{% set name = "wagtailcharts" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wagtailcharts-{{ version }}.tar.gz
  sha256: 1c1fb0ee8a47fc870767751ec3b186d2b167ede0a968d854819446c45343cefa

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - wagtail >=3.0

test:
  imports:
    - wagtailcharts
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/overcastsoftware/wagtailcharts/
  summary: Chart.js charts for Wagtail
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - rxm7706
